Basic Python

In [ ]:
type(10)
type(2.1)
type("hello")
a = [1,2,3,4,5]
print(len(a))
print(a[0])
print(a[0:2]) #elements 0-2
print(a[1:])  #elements after and including 1
print(a[:3])  #elements before and including 3
print(a[:-1]) #elements before the first element before the last element
print(a[:-2]) #elements before the second element before the last element

5
1
[1, 2]
[2, 3, 4, 5]
[1, 2, 3]
[1, 2, 3, 4]
[1, 2, 3]


Dictionary/Map

In [ ]:
# Initialization (Literal)
model_config = {
    "learning_rate": 0.001,
    "epochs": 10,
    "optimizer": "Adam"
}

# Adding or Updating
model_config["batch_size"] = 32

# Accessing (Standard)
lr = model_config["learning_rate"]

# Safe Access (Equivalent to Java's getOrDefault)
dropout = model_config.get("dropout_rate", 0.5)

# Iterating through pairs (Most common in ML)
for key, value in model_config.items():
    print(f"Hyperparameter {key} is set to {value}")

# Iterating through keys only
for key in model_config.keys():
    print(key)

In [6]:
import numpy as np
x = np.array([1,2,3])
x = x/2
print(x)
type(x)

[0.5 1.  1.5]


numpy.ndarray

In [12]:
import numpy as np
A = np.array([[1,2],[3,4]])
print(A)
print(A.shape)
print(A.dtype)
print(A*10)
B = np.array([[3,0],[0,6]])
print(A*B)
print(A+B)


[[1 2]
 [3 4]]
(2, 2)
int64
[[10 20]
 [30 40]]
[[ 3  0]
 [ 0 24]]
[[ 4  2]
 [ 3 10]]
