**D2l.ai Chapter 2**

**Data manipulation**

In [ ]:
import torch
x = torch.arange(12, dtype=torch.float32)
X = x.reshape(3, 4)
X[:2] = 12
x = torch.exp(x)
print(x)
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
print(torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1))
print(X == Y)
print(X.sum())

tensor([162754.7969, 162754.7969, 162754.7969, 162754.7969, 162754.7969,
        162754.7969, 162754.7969, 162754.7969,   2980.9580,   8103.0840,
         22026.4648,  59874.1406])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]]) tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])
tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])


Memory

In [13]:
before = id(Y)
Y = Y + X
print(id(Y) == before)
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))
before = id(X)
X += Y
id(X) == before

False
id(Z): 2658380980192
id(Z): 2658380980192


True

torch & numpy

In [ ]:
A = X.numpy()
B = torch.from_numpy(A)
print(type(A), type(B))

**Date Preprocessing**

In [1]:
import os

os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('''NumRooms,RoofType,Price
NA,NA,127500
2,NA,106000
4,Slate,178100
NA,NA,140000''')

In [2]:
import pandas as pd

data = pd.read_csv(data_file)
print(data)

   NumRooms RoofType   Price
0       NaN      NaN  127500
1       2.0      NaN  106000
2       4.0    Slate  178100
3       NaN      NaN  140000


missing data

In [3]:
inputs, targets = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = pd.get_dummies(inputs, dummy_na=True)
print(inputs)

   NumRooms  RoofType_Slate  RoofType_nan
0       NaN           False          True
1       2.0           False          True
2       4.0            True         False
3       NaN           False          True


In [4]:
inputs = inputs.fillna(inputs.mean())
print(inputs)

   NumRooms  RoofType_Slate  RoofType_nan
0       3.0           False          True
1       2.0           False          True
2       4.0            True         False
3       3.0           False          True


Convert to tensor

In [5]:
import torch

X = torch.tensor(inputs.to_numpy(dtype=float))
y = torch.tensor(targets.to_numpy(dtype=float))
X, y

(tensor([[3., 0., 1.],
         [2., 0., 1.],
         [4., 1., 0.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500., 106000., 178100., 140000.], dtype=torch.float64))

Linear Algebra

In [1]:
import torch
A = torch.arange(6).reshape(3, 2)
print(A.T)

tensor([[0, 2, 4],
        [1, 3, 5]])


In [2]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
B = A.clone()  # Assign a copy of A to B by allocating new memory
print(A, A + B)

tensor([[0., 1., 2.],
        [3., 4., 5.]]) tensor([[ 0.,  2.,  4.],
        [ 6.,  8., 10.]])


In [ ]:
x = torch.arange(3, dtype=torch.float32)
print(x, x.sum())

Reduction(Sum, Mean)

In [ ]:
A.shape, A.sum()
A.shape, A.sum(axis=0).shape
A.shape, A.sum(axis=1).shape
A.sum(axis=[0, 1]) == A.sum()  # Same as A.sum()
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

Non-reduction Sum

In [3]:
sum_A = A.sum(axis=1, keepdims=True)
print(sum_A, sum_A.shape)

tensor([[ 3.],
        [12.]]) torch.Size([2, 1])


Dot product

In [5]:
x = torch.arange(3, dtype=torch.float32)
y = torch.ones(3, dtype = torch.float32)
print(x, y, torch.dot(x, y))

tensor([0., 1., 2.]) tensor([1., 1., 1.]) tensor(3.)


Vector product

In [7]:
print(A.shape, x.shape, torch.mv(A, x), A@x)
B = torch.ones(3, 4)
print(torch.mm(A, B), A@B)

torch.Size([2, 3]) torch.Size([3]) tensor([ 5., 14.]) tensor([ 5., 14.])
tensor([[ 3.,  3.,  3.,  3.],
        [12., 12., 12., 12.]]) tensor([[ 3.,  3.,  3.,  3.],
        [12., 12., 12., 12.]])


Norm

In [ ]:
u = torch.tensor([3.0, -4.0])
print(torch.norm(u))  #l_2 norm
print(torch.abs(u).sum())  #l_1 norm

**Automatic Differentiation**

In [3]:
import torch

In [6]:
x = torch.arange(4.0)
print(x)
# Can also create x = torch.arange(4.0, requires_grad=True)
x.requires_grad_(True)
print(x.grad) # The gradient is None by default

tensor([0., 1., 2., 3.])
None


In [9]:
y = 2 * torch.dot(x, x)
print(y)
y.backward()
print(x.grad)
print(x.grad == 4 * x)

tensor(28., grad_fn=<MulBackward0>)
tensor([ 0., 12., 24., 36.])
tensor([ True, False, False, False])
